export const wordLists = {
  basicWords: [
    { swedish: "jag", italian: "io", japanese: "watashi" },
    { swedish: "du", italian: "tu", japanese: "anata" },
    { swedish: "han", italian: "lui", japanese: "kare" },
    { swedish: "hon", italian: "lei", japanese: "kanojo" },
    { swedish: "det", italian: "esso/essa", japanese: "sore" },
    { swedish: "vi", italian: "noi", japanese: "watashitachi" },
    { swedish: "ni", italian: "voi", japanese: "anatatachi" },
    { swedish: "de", italian: "loro", japanese: "karera" },
    { swedish: "är", italian: "essere", japanese: "desu" },
    { swedish: "har", italian: "avere", japanese: "motte iru" },
    { swedish: "inte", italian: "non", japanese: "nai" },
    { swedish: "på", italian: "su", japanese: "ni" },
    { swedish: "och", italian: "e", japanese: "to" },
    { swedish: "att", italian: "che", japanese: "koto" },
    { swedish: "en", italian: "un/uno", japanese: "hitotsu" },
    { swedish: "i", italian: "in", japanese: "ni" },
    { swedish: "som", italian: "come", japanese: "youni" },
    { swedish: "för", italian: "per", japanese: "tame ni" },
    { swedish: "med", italian: "con", japanese: "to" },
    { swedish: "av", italian: "di", japanese: "no" },
    { swedish: "till", italian: "a", japanese: "e" },
    { swedish: "kan", italian: "potere", japanese: "dekiru" },
    { swedish: "om", italian: "se", japanese: "moshi" },
    { swedish: "så", italian: "così", japanese: "sou" },
    { swedish: "men", italian: "ma", japanese: "shikashi" },
    { swedish: "när", italian: "quando", japanese: "itsu" },
    { swedish: "vad", italian: "cosa", japanese: "nani" },
    { swedish: "hur", italian: "come", japanese: "dou" },
    { swedish: "där", italian: "lì", japanese: "soko" },
    { swedish: "här", italian: "qui", japanese: "koko" },
    { swedish: "från", italian: "da", japanese: "kara" },
    { swedish: "eller", italian: "o", japanese: "matawa" },
    { swedish: "nu", italian: "ora", japanese: "ima" },
    { swedish: "efter", italian: "dopo", japanese: "ato" },
    { swedish: "bara", italian: "solo", japanese: "tada" },
    { swedish: "också", italian: "anche", japanese: "mo" },
    { swedish: "få", italian: "ottenere", japanese: "eru" },
    { swedish: "då", italian: "allora", japanese: "sono toki" },
    { swedish: "skulle", italian: "dovrebbe", japanese: "beki" },
    { swedish: "alla", italian: "tutti", japanese: "minna" },
    { swedish: "mot", italian: "contro", japanese: "ni taishite" },
    { swedish: "under", italian: "sotto", japanese: "shita" },
    { swedish: "år", italian: "anno", japanese: "toshi" },
    { swedish: "två", italian: "due", japanese: "ni" },
    { swedish: "vill", italian: "volere", japanese: "hoshii" },
    { swedish: "mellan", italian: "tra", japanese: "aida" },
    { swedish: "många", italian: "molti", japanese: "ooi" },
    { swedish: "något", italian: "qualcosa", japanese: "nanika" },
    { swedish: "över", italian: "sopra", japanese: "ue" },
    { swedish: "mycket", italian: "molto", japanese: "totemo" },
  ],
  colors: [
    { swedish: "röd", italian: "rosso", japanese: "aka" },
    { swedish: "blå", italian: "blu", japanese: "ao" },
    { swedish: "grön", italian: "verde", japanese: "midori" },
    { swedish: "gul", italian: "giallo", japanese: "kiiro" },
    { swedish: "svart", italian: "nero", japanese: "kuro" },
    { swedish: "vit", italian: "bianco", japanese: "shiro" },
  ],
  numbers: [
    { swedish: "ett", italian: "uno", japanese: "ichi" },
    { swedish: "två", italian: "due", japanese: "ni" },
    { swedish: "tre", italian: "tre", japanese: "san" },
    { swedish: "fyra", italian: "quattro", japanese: "yon" },
    { swedish: "fem", italian: "cinque", japanese: "go" },
  ],
  animals: [
    { swedish: "hund", italian: "cane", japanese: "inu" },
    { swedish: "katt", italian: "gatto", japanese: "neko" },
    { swedish: "fågel", italian: "uccello", japanese: "tori" },
    { swedish: "fisk", italian: "pesce", japanese: "sakana" },
    { swedish: "häst", italian: "cavallo", japanese: "uma" },
  ],
  foodAndDrink: [
    { swedish: "äpple", italian: "mela", japanese: "ringo" },
    { swedish: "bröd", italian: "pane", japanese: "pan" },
    { swedish: "vatten", italian: "acqua", japanese: "mizu" },
    { swedish: "kaffe", italian: "caffè", japanese: "koohii" },
    { swedish: "ost", italian: "formaggio", japanese: "chiizu" },
    { swedish: "kött", italian: "carne", japanese: "niku" },
    { swedish: "fisk", italian: "pesce", japanese: "sakana" },
    { swedish: "ris", italian: "riso", japanese: "gohan" },
    { swedish: "pasta", italian: "pasta", japanese: "pasuta" },
    { swedish: "soppa", italian: "zuppa", japanese: "suupu" },
    { swedish: "grönsak", italian: "verdura", japanese: "yasai" },
    { swedish: "frukt", italian: "frutta", japanese: "kudamono" },
    { swedish: "mjölk", italian: "latte", japanese: "gyuunyuu" },
    { swedish: "juice", italian: "succo", japanese: "juusu" },
    { swedish: "te", italian: "tè", japanese: "ocha" },
  ],
  bodyParts: [
    { swedish: "huvud", italian: "testa", japanese: "atama" },
    { swedish: "arm", italian: "braccio", japanese: "ude" },
    { swedish: "ben", italian: "gamba", japanese: "ashi" },
    { swedish: "hand", italian: "mano", japanese: "te" },
    { swedish: "fot", italian: "piede", japanese: "ashi" },
    { swedish: "öga", italian: "occhio", japanese: "me" },
    { swedish: "näsa", italian: "naso", japanese: "hana" },
    { swedish: "mun", italian: "bocca", japanese: "kuchi" },
    { swedish: "öra", italian: "orecchio", japanese: "mimi" },
    { swedish: "hår", italian: "capelli", japanese: "kami" },
  ],
  clothing: [
    { swedish: "skjorta", italian: "camicia", japanese: "shatsu" },
    { swedish: "byxor", italian: "pantaloni", japanese: "zubon" },
    { swedish: "klänning", italian: "vestito", japanese: "doresu" },
    { swedish: "skor", italian: "scarpe", japanese: "kutsu" },
    { swedish: "strumpor", italian: "calzini", japanese: "kutsushita" },
    { swedish: "jacka", italian: "giacca", japanese: "jaketto" },
    { swedish: "hatt", italian: "cappello", japanese: "boushi" },
    { swedish: "kjol", italian: "gonna", japanese: "sukaato" },
    { swedish: "tröja", italian: "maglione", japanese: "seetaa" },
    { swedish: "kostym", italian: "completo", japanese: "suutsu" },
    { swedish: "slips", italian: "cravatta", japanese: "nekutai" },
    { swedish: "handskar", italian: "guanti", japanese: "tebukuro" },
  ],
  weather: [
    { swedish: "sol", italian: "sole", japanese: "taiyou" },
    { swedish: "regn", italian: "pioggia", japanese: "ame" },
    { swedish: "snö", italian: "neve", japanese: "yuki" },
    { swedish: "vind", italian: "vento", japanese: "kaze" },
    { swedish: "moln", italian: "nuvola", japanese: "kumo" },
    { swedish: "storm", italian: "tempesta", japanese: "arashi" },
    { swedish: "dimma", italian: "nebbia", japanese: "kiri" },
    { swedish: "åska", italian: "tuono", japanese: "kaminari" },
    { swedish: "blixt", italian: "fulmine", japanese: "inazuma" },
    { swedish: "hagel", italian: "grandine", japanese: "hyou" },
  ],
  professions: [
    { swedish: "lärare", italian: "insegnante", japanese: "kyoushi" },
    { swedish: "läkare", italian: "medico", japanese: "isha" },
    { swedish: "kock", italian: "cuoco", japanese: "kokkusan" },
    { swedish: "polis", italian: "poliziotto", japanese: "keisatsu" },
    { swedish: "ingenjör", italian: "ingegnere", japanese: "enjinia" },
    { swedish: "advokat", italian: "avvocato", japanese: "bengoshi" },
    { swedish: "konstnär", italian: "artista", japanese: "geijutsuka" },
    { swedish: "skådespelare", italian: "attore", japanese: "haiyuu" },
    { swedish: "musiker", italian: "musicista", japanese: "ongakuka" },
    { swedish: "författare", italian: "scrittore", japanese: "sakka" },
    { swedish: "sjuksköterska", italian: "infermiere", japanese: "kangoshi" },
    { swedish: "pilot", italian: "pilota", japanese: "pairotto" },
    { swedish: "frisör", italian: "parrucchiere", japanese: "biyoushi" },
    { swedish: "arkitekt", italian: "architetto", japanese: "kenchikuka" },
    { swedish: "journalist", italian: "giornalista", japanese: "kisha" },
  ],
  transportation: [
    { swedish: "bil", italian: "automobile", japanese: "kuruma" },
    { swedish: "buss", italian: "autobus", japanese: "basu" },
    { swedish: "tåg", italian: "treno", japanese: "densha" },
    { swedish: "flygplan", italian: "aereo", japanese: "hikouki" },
    { swedish: "cykel", italian: "bicicletta", japanese: "jitensha" },
    { swedish: "båt", italian: "barca", japanese: "fune" },
    { swedish: "motorcykel", italian: "motocicletta", japanese: "ootobaai" },
    { swedish: "tunnelbana", italian: "metropolitana", japanese: "chikatetsu" },
    { swedish: "taxi", italian: "taxi", japanese: "takushii" },
    { swedish: "helikopter", italian: "elicottero", japanese: "herikoputaa" },
  ],
  furniture: [
    { swedish: "stol", italian: "sedia", japanese: "isu" },
    { swedish: "bord", italian: "tavolo", japanese: "teeburu" },
    { swedish: "säng", italian: "letto", japanese: "beddo" },
    { swedish: "soffa", italian: "divano", japanese: "sofa" },
    { swedish: "skåp", italian: "armadio", japanese: "tansu" },
    { swedish: "bokhylla", italian: "libreria", japanese: "hondana" },
    { swedish: "matta", italian: "tappeto", japanese: "juutan" },
    { swedish: "lampa", italian: "lampada", japanese: "ranpu" },
    { swedish: "spegel", italian: "specchio", japanese: "kagami" },
    { swedish: "gardin", italian: "tenda", japanese: "kaaten" },
    { swedish: "kudde", italian: "cuscino", japanese: "makura" },
    { swedish: "fåtölj", italian: "poltrona", japanese: "isu" },
  ],
  emotions: [
    { swedish: "glad", italian: "felice", japanese: "ureshii" },
    { swedish: "ledsen", italian: "triste", japanese: "kanashii" },
    { swedish: "arg", italian: "arrabbiato", japanese: "okotta" },
    { swedish: "rädd", italian: "spaventato", japanese: "kowai" },
    { swedish: "överraskad", italian: "sorpreso", japanese: "odoroita" },
    { swedish: "förvirrad", italian: "confuso", japanese: "konwaku shita" },
    { swedish: "lugn", italian: "calmo", japanese: "ochitsuita" },
    { swedish: "stressad", italian: "stressato", japanese: "sutoresu ga aru" },
    { swedish: "uttråkad", italian: "annoiato", japanese: "taikutsu na" },
    { swedish: "nyfiken", italian: "curioso", japanese: "koukishin ga aru" },
    { swedish: "avundsjuk", italian: "geloso", japanese: "shitto shita" },
    { swedish: "stolt", italian: "orgoglioso", japanese: "hokori ni omou" },
    { swedish: "skamsen", italian: "imbarazzato", japanese: "hazukashii" },
    { swedish: "lättad", italian: "sollevato", japanese: "hootto shita" },
    { swedish: "entusiastisk", italian: "entusiasta", japanese: "nesshin na" },
  ],
};
