export const wordLists = {
  basicWords: [
    { swedish: "jag", italian: "io", japanese: "watashi" },
    { swedish: "du", italian: "tu", japanese: "anata" },
    { swedish: "han", italian: "lui", japanese: "kare" },
    { swedish: "hon", italian: "lei", japanese: "kanojo" },
    { swedish: "det", italian: "esso/essa", japanese: "sore" },
    { swedish: "vi", italian: "noi", japanese: "watashitachi" },
    { swedish: "ni", italian: "voi", japanese: "anatatachi" },
    { swedish: "de", italian: "loro", japanese: "karera" },
    { swedish: "är", italian: "essere", japanese: "desu" },
    { swedish: "har", italian: "avere", japanese: "motte iru" },
    { swedish: "inte", italian: "non", japanese: "nai" },
    { swedish: "på", italian: "su", japanese: "ni" },
    { swedish: "och", italian: "e", japanese: "to" },
    { swedish: "att", italian: "che", japanese: "koto" },
    { swedish: "en", italian: "un/uno", japanese: "hitotsu" },
    { swedish: "i", italian: "in", japanese: "ni" },
    { swedish: "som", italian: "come", japanese: "youni" },
    { swedish: "för", italian: "per", japanese: "tame ni" },
    { swedish: "med", italian: "con", japanese: "to" },
    { swedish: "av", italian: "di", japanese: "no" },
    { swedish: "till", italian: "a", japanese: "e" },
    { swedish: "kan", italian: "potere", japanese: "dekiru" },
    { swedish: "om", italian: "se", japanese: "moshi" },
    { swedish: "så", italian: "così", japanese: "sou" },
    { swedish: "men", italian: "ma", japanese: "shikashi" },
    { swedish: "när", italian: "quando", japanese: "itsu" },
    { swedish: "vad", italian: "cosa", japanese: "nani" },
    { swedish: "hur", italian: "come", japanese: "dou" },
    { swedish: "där", italian: "lì", japanese: "soko" },
    { swedish: "här", italian: "qui", japanese: "koko" },
    { swedish: "från", italian: "da", japanese: "kara" },
    { swedish: "eller", italian: "o", japanese: "matawa" },
    { swedish: "nu", italian: "ora", japanese: "ima" },
    { swedish: "efter", italian: "dopo", japanese: "ato" },
    { swedish: "bara", italian: "solo", japanese: "tada" },
    { swedish: "också", italian: "anche", japanese: "mo" },
    { swedish: "få", italian: "ottenere", japanese: "eru" },
    { swedish: "då", italian: "allora", japanese: "sono toki" },
    { swedish: "skulle", italian: "dovrebbe", japanese: "beki" },
    { swedish: "alla", italian: "tutti", japanese: "minna" },
    { swedish: "mot", italian: "contro", japanese: "ni taishite" },
    { swedish: "under", italian: "sotto", japanese: "shita" },
    { swedish: "år", italian: "anno", japanese: "toshi" },
    { swedish: "två", italian: "due", japanese: "ni" },
    { swedish: "vill", italian: "volere", japanese: "hoshii" },
    { swedish: "mellan", italian: "tra", japanese: "aida" },
    { swedish: "många", italian: "molti", japanese: "ooi" },
    { swedish: "något", italian: "qualcosa", japanese: "nanika" },
    { swedish: "över", italian: "sopra", japanese: "ue" },
    { swedish: "mycket", italian: "molto", japanese: "totemo" },
  ],
  colors: [
    { swedish: "röd", italian: "rosso", japanese: "aka" },
    { swedish: "blå", italian: "blu", japanese: "ao" },
    { swedish: "grön", italian: "verde", japanese: "midori" },
    { swedish: "gul", italian: "giallo", japanese: "kiiro" },
    { swedish: "svart", italian: "nero", japanese: "kuro" },
    { swedish: "vit", italian: "bianco", japanese: "shiro" },
  ],
  numbers: [
    { swedish: "ett", italian: "uno", japanese: "ichi" },
    { swedish: "två", italian: "due", japanese: "ni" },
    { swedish: "tre", italian: "tre", japanese: "san" },
    { swedish: "fyra", italian: "quattro", japanese: "yon" },
    { swedish: "fem", italian: "cinque", japanese: "go" },
    { swedish: "sex", italian: "sei", japanese: "roku" },
    { swedish: "sju", italian: "sette", japanese: "nana" },
    { swedish: "åtta", italian: "otto", japanese: "hachi" },
    { swedish: "nio", italian: "nove", japanese: "kyuu" },
    { swedish: "tio", italian: "dieci", japanese: "juu" },
  ],
  animals: [
    { swedish: "hund", italian: "cane", japanese: "inu" },
    { swedish: "katt", italian: "gatto", japanese: "neko" },
    { swedish: "fågel", italian: "uccello", japanese: "tori" },
    { swedish: "fisk", italian: "pesce", japanese: "sakana" },
    { swedish: "häst", italian: "cavallo", japanese: "uma" },
  ],
  foodAndDrink: [
    { swedish: "äpple", italian: "mela", japanese: "ringo" },
    { swedish: "bröd", italian: "pane", japanese: "pan" },
    { swedish: "vatten", italian: "acqua", japanese: "mizu" },
    { swedish: "kaffe", italian: "caffè", japanese: "koohii" },
    { swedish: "ost", italian: "formaggio", japanese: "chiizu" },
    { swedish: "kött", italian: "carne", japanese: "niku" },
    { swedish: "fisk", italian: "pesce", japanese: "sakana" },
    { swedish: "ris", italian: "riso", japanese: "gohan" },
    { swedish: "pasta", italian: "pasta", japanese: "pasuta" },
    { swedish: "soppa", italian: "zuppa", japanese: "suupu" },
    { swedish: "grönsak", italian: "verdura", japanese: "yasai" },
    { swedish: "frukt", italian: "frutta", japanese: "kudamono" },
    { swedish: "mjölk", italian: "latte", japanese: "gyuunyuu" },
    { swedish: "juice", italian: "succo", japanese: "juusu" },
    { swedish: "te", italian: "tè", japanese: "ocha" },
  ],
  bodyParts: [
    { swedish: "huvud", italian: "testa", japanese: "atama" },
    { swedish: "arm", italian: "braccio", japanese: "ude" },
    { swedish: "ben", italian: "gamba", japanese: "ashi" },
    { swedish: "hand", italian: "mano", japanese: "te" },
    { swedish: "fot", italian: "piede", japanese: "ashi" },
    { swedish: "öga", italian: "occhio", japanese: "me" },
    { swedish: "näsa", italian: "naso", japanese: "hana" },
    { swedish: "mun", italian: "bocca", japanese: "kuchi" },
    { swedish: "öra", italian: "orecchio", japanese: "mimi" },
    { swedish: "hår", italian: "capelli", japanese: "kami" },
  ],
  clothing: [
    { swedish: "skjorta", italian: "camicia", japanese: "shatsu" },
    { swedish: "byxor", italian: "pantaloni", japanese: "zubon" },
    { swedish: "klänning", italian: "vestito", japanese: "doresu" },
    { swedish: "skor", italian: "scarpe", japanese: "kutsu" },
    { swedish: "strumpor", italian: "calzini", japanese: "kutsushita" },
    { swedish: "jacka", italian: "giacca", japanese: "jaketto" },
    { swedish: "hatt", italian: "cappello", japanese: "boushi" },
    { swedish: "kjol", italian: "gonna", japanese: "sukaato" },
    { swedish: "tröja", italian: "maglione", japanese: "seetaa" },
    { swedish: "kostym", italian: "completo", japanese: "suutsu" },
    { swedish: "slips", italian: "cravatta", japanese: "nekutai" },
    { swedish: "handskar", italian: "guanti", japanese: "tebukuro" },
  ],
  weather: [
    { swedish: "sol", italian: "sole", japanese: "taiyou" },
    { swedish: "regn", italian: "pioggia", japanese: "ame" },
    { swedish: "snö", italian: "neve", japanese: "yuki" },
    { swedish: "vind", italian: "vento", japanese: "kaze" },
    { swedish: "moln", italian: "nuvola", japanese: "kumo" },
    { swedish: "storm", italian: "tempesta", japanese: "arashi" },
    { swedish: "dimma", italian: "nebbia", japanese: "kiri" },
    { swedish: "åska", italian: "tuono", japanese: "kaminari" },
    { swedish: "blixt", italian: "fulmine", japanese: "inazuma" },
    { swedish: "hagel", italian: "grandine", japanese: "hyou" },
  ],
  professions: [
    { swedish: "lärare", italian: "insegnante", japanese: "kyoushi" },
    { swedish: "läkare", italian: "medico", japanese: "isha" },
    { swedish: "kock", italian: "cuoco", japanese: "kokkusan" },
    { swedish: "polis", italian: "poliziotto", japanese: "keisatsu" },
    { swedish: "ingenjör", italian: "ingegnere", japanese: "enjinia" },
    { swedish: "advokat", italian: "avvocato", japanese: "bengoshi" },
    { swedish: "konstnär", italian: "artista", japanese: "geijutsuka" },
    { swedish: "skådespelare", italian: "attore", japanese: "haiyuu" },
    { swedish: "musiker", italian: "musicista", japanese: "ongakuka" },
    { swedish: "författare", italian: "scrittore", japanese: "sakka" },
    { swedish: "sjuksköterska", italian: "infermiere", japanese: "kangoshi" },
    { swedish: "pilot", italian: "pilota", japanese: "pairotto" },
    { swedish: "frisör", italian: "parrucchiere", japanese: "biyoushi" },
    { swedish: "arkitekt", italian: "architetto", japanese: "kenchikuka" },
    { swedish: "journalist", italian: "giornalista", japanese: "kisha" },
  ],
  transportation: [
    { swedish: "bil", italian: "automobile", japanese: "kuruma" },
    { swedish: "buss", italian: "autobus", japanese: "basu" },
    { swedish: "tåg", italian: "treno", japanese: "densha" },
    { swedish: "flygplan", italian: "aereo", japanese: "hikouki" },
    { swedish: "cykel", italian: "bicicletta", japanese: "jitensha" },
    { swedish: "båt", italian: "barca", japanese: "fune" },
    { swedish: "motorcykel", italian: "motocicletta", japanese: "ootobaai" },
    { swedish: "tunnelbana", italian: "metropolitana", japanese: "chikatetsu" },
    { swedish: "taxi", italian: "taxi", japanese: "takushii" },
    { swedish: "helikopter", italian: "elicottero", japanese: "herikoputaa" },
  ],
  furniture: [
    { swedish: "stol", italian: "sedia", japanese: "isu" },
    { swedish: "bord", italian: "tavolo", japanese: "teeburu" },
    { swedish: "säng", italian: "letto", japanese: "beddo" },
    { swedish: "soffa", italian: "divano", japanese: "sofa" },
    { swedish: "skåp", italian: "armadio", japanese: "tansu" },
    { swedish: "bokhylla", italian: "libreria", japanese: "hondana" },
    { swedish: "matta", italian: "tappeto", japanese: "juutan" },
    { swedish: "lampa", italian: "lampada", japanese: "ranpu" },
    { swedish: "spegel", italian: "specchio", japanese: "kagami" },
    { swedish: "gardin", italian: "tenda", japanese: "kaaten" },
    { swedish: "kudde", italian: "cuscino", japanese: "makura" },
    { swedish: "fåtölj", italian: "poltrona", japanese: "isu" },
  ],
  emotions: [
    { swedish: "glad", italian: "felice", japanese: "ureshii" },
    { swedish: "ledsen", italian: "triste", japanese: "kanashii" },
    { swedish: "arg", italian: "arrabbiato", japanese: "okotta" },
    { swedish: "rädd", italian: "spaventato", japanese: "kowai" },
    { swedish: "överraskad", italian: "sorpreso", japanese: "odoroita" },
    { swedish: "förvirrad", italian: "confuso", japanese: "konwaku shita" },
    { swedish: "lugn", italian: "calmo", japanese: "ochitsuita" },
    { swedish: "stressad", italian: "stressato", japanese: "sutoresu ga aru" },
    { swedish: "uttråkad", italian: "annoiato", japanese: "taikutsu na" },
    { swedish: "nyfiken", italian: "curioso", japanese: "koukishin ga aru" },
    { swedish: "avundsjuk", italian: "geloso", japanese: "shitto shita" },
    { swedish: "stolt", italian: "orgoglioso", japanese: "hokori ni omou" },
    { swedish: "skamsen", italian: "imbarazzato", japanese: "hazukashii" },
    { swedish: "lättad", italian: "sollevato", japanese: "hootto shita" },
    { swedish: "entusiastisk", italian: "entusiasta", japanese: "nesshin na" },
  ],
  family: [
    { swedish: "mor", italian: "madre", japanese: "haha" },
    { swedish: "far", italian: "padre", japanese: "chichi" },
    { swedish: "syster", italian: "sorella", japanese: "ane" },
    { swedish: "bror", italian: "fratello", japanese: "ani" },
    { swedish: "mormor", italian: "nonna", japanese: "sobo" },
    { swedish: "morfar", italian: "nonno", japanese: "sofu" },
    { swedish: "kusin", italian: "cugino", japanese: "itoko" },
    { swedish: "moster", italian: "zia", japanese: "oba" },
    { swedish: "farbror", italian: "zio", japanese: "oji" },
    { swedish: "svägerska", italian: "cognata", japanese: "giri no ane" },
  ],
  
  sports: [
    { swedish: "fotboll", italian: "calcio", japanese: "sakkaa" },
    { swedish: "tennis", italian: "tennis", japanese: "tenisu" },
    { swedish: "simning", italian: "nuoto", japanese: "suiei" },
    { swedish: "basket", italian: "pallacanestro", japanese: "basukettoboru" },
    { swedish: "golf", italian: "golf", japanese: "gorufu" },
    { swedish: "skidor", italian: "sci", japanese: "sukii" },
    { swedish: "löpning", italian: "corsa", japanese: "hashiru" },
    { swedish: "volleyboll", italian: "pallavolo", japanese: "barebooru" },
    { swedish: "gymnastik", italian: "ginnastica", japanese: "taisou" },
    { swedish: "boxning", italian: "pugilato", japanese: "bokushingu" },
  ],
  
  technology: [
    { swedish: "dator", italian: "computer", japanese: "konpyuuta" },
    { swedish: "smartphone", italian: "smartphone", japanese: "sumaho" },
    { swedish: "internet", italian: "internet", japanese: "intaanetto" },
    { swedish: "programvara", italian: "software", japanese: "sofutowea" },
    { swedish: "nätverk", italian: "rete", japanese: "nettowaku" },
    { swedish: "molnet", italian: "cloud", japanese: "kuraudo" },
    { swedish: "artificiell intelligens", italian: "intelligenza artificiale", japanese: "jinkou chinou" },
    { swedish: "virtuell verklighet", italian: "realtà virtuale", japanese: "baacharu riariti" },
    { swedish: "cybersäkerhet", italian: "cybersicurezza", japanese: "saibaa sekyuriti" },
    { swedish: "blockkedja", italian: "blockchain", japanese: "burokkucheen" },
  ],
  
  nature: [
    { swedish: "träd", italian: "albero", japanese: "ki" },
    { swedish: "flod", italian: "fiume", japanese: "kawa" },
    { swedish: "berg", italian: "montagna", japanese: "yama" },
    { swedish: "skog", italian: "foresta", japanese: "mori" },
    { swedish: "strand", italian: "spiaggia", japanese: "hama" },
    { swedish: "sjö", italian: "lago", japanese: "mizuumi" },
    { swedish: "öken", italian: "deserto", japanese: "sabaku" },
    { swedish: "vulkan", italian: "vulcano", japanese: "kazan" },
    { swedish: "glaciär", italian: "ghiacciaio", japanese: "hyouga" },
    { swedish: "dal", italian: "valle", japanese: "tani" },
  ],
  
  hobbies: [
    { swedish: "läsning", italian: "lettura", japanese: "dokusho" },
    { swedish: "matlagning", italian: "cucina", japanese: "ryouri" },
    { swedish: "trädgårdsarbete", italian: "giardinaggio", japanese: "engei" },
    { swedish: "fotografering", italian: "fotografia", japanese: "shashin" },
    { swedish: "målning", italian: "pittura", japanese: "kaiga" },
    { swedish: "dans", italian: "danza", japanese: "dansu" },
    { swedish: "fiske", italian: "pesca", japanese: "tsuri" },
    { swedish: "stickning", italian: "maglia", japanese: "amimono" },
    { swedish: "skrivande", italian: "scrittura", japanese: "sakubun" },
    { swedish: "samla", italian: "collezionismo", japanese: "shumi no shuushuu" },
  ],
  
  countries: [
    { swedish: "Sverige", italian: "Svezia", japanese: "Suweeden" },
    { swedish: "Italien", italian: "Italia", japanese: "Itaria" },
    { swedish: "Japan", italian: "Giappone", japanese: "Nihon" },
    { swedish: "USA", italian: "Stati Uniti", japanese: "Amerika" },
    { swedish: "Frankrike", italian: "Francia", japanese: "Furansu" },
    { swedish: "Tyskland", italian: "Germania", japanese: "Doitsu" },
    { swedish: "Kina", italian: "Cina", japanese: "Chuugoku" },
    { swedish: "Brasilien", italian: "Brasile", japanese: "Burajiru" },
    { swedish: "Australien", italian: "Australia", japanese: "Oosutoraria" },
    { swedish: "Indien", italian: "India", japanese: "Indo" },
  ],
  
  school: [
    { swedish: "klassrum", italian: "aula", japanese: "kyoushitsu" },
    { swedish: "lärare", italian: "insegnante", japanese: "sensei" },
    { swedish: "elev", italian: "studente", japanese: "seito" },
    { swedish: "läxa", italian: "compiti", japanese: "shukudai" },
    { swedish: "penna", italian: "penna", japanese: "pen" },
    { swedish: "anteckningsbok", italian: "quaderno", japanese: "nooto" },
    { swedish: "tavla", italian: "lavagna", japanese: "kokuban" },
    { swedish: "schema", italian: "orario", japanese: "jikanwari" },
    { swedish: "examen", italian: "esame", japanese: "shiken" },
    { swedish: "bibliotek", italian: "biblioteca", japanese: "toshokan" },
  ],
  
  time: [
    { swedish: "sekund", italian: "secondo", japanese: "byou" },
    { swedish: "minut", italian: "minuto", japanese: "fun" },
    { swedish: "timme", italian: "ora", japanese: "jikan" },
    { swedish: "dag", italian: "giorno", japanese: "hi" },
    { swedish: "vecka", italian: "settimana", japanese: "shuukan" },
    { swedish: "månad", italian: "mese", japanese: "tsuki" },
    { swedish: "år", italian: "anno", japanese: "toshi" },
    { swedish: "decennium", italian: "decennio", japanese: "juunen" },
    { swedish: "århundrade", italian: "secolo", japanese: "seiki" },
    { swedish: "årtusende", italian: "millennio", japanese: "sennen" },
  ],
  
  music: [
    { swedish: "gitarr", italian: "chitarra", japanese: "gitaa" },
    { swedish: "piano", italian: "pianoforte", japanese: "piano" },
    { swedish: "trummor", italian: "batteria", japanese: "doramu" },
    { swedish: "violin", italian: "violino", japanese: "baiorin" },
    { swedish: "flöjt", italian: "flauto", japanese: "furuuto" },
    { swedish: "saxofon", italian: "sassofono", japanese: "sakusofon" },
    { swedish: "trumpet", italian: "tromba", japanese: "toranpetto" },
    { swedish: "klarinett", italian: "clarinetto", japanese: "kurarinetto" },
    { swedish: "harpa", italian: "arpa", japanese: "haapu" },
    { swedish: "cello", italian: "violoncello", japanese: "chero" },
  ],
  
  vehicles: [
    { swedish: "bil", italian: "automobile", japanese: "jidousha" },
    { swedish: "motorcykel", italian: "motocicletta", japanese: "ootobaai" },
    { swedish: "lastbil", italian: "camion", japanese: "torakku" },
    { swedish: "buss", italian: "autobus", japanese: "basu" },
    { swedish: "tåg", italian: "treno", japanese: "densha" },
    { swedish: "flygplan", italian: "aereo", japanese: "hikouki" },
    { swedish: "helikopter", italian: "elicottero", japanese: "herikoputaa" },
    { swedish: "båt", italian: "barca", japanese: "fune" },
    { swedish: "ubåt", italian: "sottomarino", japanese: "sensuikan" },
    { swedish: "rymdskepp", italian: "astronave", japanese: "uchuu sen" },
  ],
};
