export const wordList = [
  { swedish: "jag", italian: "io", japanese: "watashi" },
  { swedish: "du", italian: "tu", japanese: "anata" },
  { swedish: "han", italian: "lui", japanese: "kare" },
  { swedish: "hon", italian: "lei", japanese: "kanojo" },
  { swedish: "det", italian: "esso/essa", japanese: "sore" },
  { swedish: "vi", italian: "noi", japanese: "watashitachi" },
  { swedish: "ni", italian: "voi", japanese: "anatatachi" },
  { swedish: "de", italian: "loro", japanese: "karera" },
  { swedish: "är", italian: "essere", japanese: "desu" },
  { swedish: "har", italian: "avere", japanese: "motte iru" },
  { swedish: "inte", italian: "non", japanese: "nai" },
  { swedish: "på", italian: "su", japanese: "ni" },
  { swedish: "och", italian: "e", japanese: "to" },
  { swedish: "att", italian: "che", japanese: "koto" },
  { swedish: "en", italian: "un/uno", japanese: "hitotsu" },
  { swedish: "i", italian: "in", japanese: "ni" },
  { swedish: "som", italian: "come", japanese: "youni" },
  { swedish: "för", italian: "per", japanese: "tame ni" },
  { swedish: "med", italian: "con", japanese: "to" },
  { swedish: "av", italian: "di", japanese: "no" },
  { swedish: "till", italian: "a", japanese: "e" },
  { swedish: "kan", italian: "potere", japanese: "dekiru" },
  { swedish: "om", italian: "se", japanese: "moshi" },
  { swedish: "så", italian: "così", japanese: "sou" },
  { swedish: "men", italian: "ma", japanese: "shikashi" },
  { swedish: "när", italian: "quando", japanese: "itsu" },
  { swedish: "vad", italian: "cosa", japanese: "nani" },
  { swedish: "hur", italian: "come", japanese: "dou" },
  { swedish: "där", italian: "lì", japanese: "soko" },
  { swedish: "här", italian: "qui", japanese: "koko" },
  { swedish: "från", italian: "da", japanese: "kara" },
  { swedish: "eller", italian: "o", japanese: "matawa" },
  { swedish: "nu", italian: "ora", japanese: "ima" },
  { swedish: "efter", italian: "dopo", japanese: "ato" },
  { swedish: "bara", italian: "solo", japanese: "tada" },
  { swedish: "också", italian: "anche", japanese: "mo" },
  { swedish: "få", italian: "ottenere", japanese: "eru" },
  { swedish: "då", italian: "allora", japanese: "sono toki" },
  { swedish: "skulle", italian: "dovrebbe", japanese: "beki" },
  { swedish: "alla", italian: "tutti", japanese: "minna" },
  { swedish: "mot", italian: "contro", japanese: "ni taishite" },
  { swedish: "under", italian: "sotto", japanese: "shita" },
  { swedish: "år", italian: "anno", japanese: "toshi" },
  { swedish: "två", italian: "due", japanese: "ni" },
  { swedish: "vill", italian: "volere", japanese: "hoshii" },
  { swedish: "mellan", italian: "tra", japanese: "aida" },
  { swedish: "många", italian: "molti", japanese: "ooi" },
  { swedish: "något", italian: "qualcosa", japanese: "nanika" },
  { swedish: "över", italian: "sopra", japanese: "ue" },
  { swedish: "mycket", italian: "molto", japanese: "totemo" }
];
